[package]
name = "bitrle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
image = "0.24"
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"
